### ISSUE TITLE
Make it work in the browser

### ISSUE THREAD

**Issue by wokalski** [dialohq/inline-test-ppx#2]
We should only run the tests in node environment. In the web environment they should be skipped. I suppose we should wrap the tests in an `if` that will run conditionally. The only problem I can see is that the `imports` will be generated regardless by rescript which might break the behavior in the browser. Not sure how to address that.

**Comment by tsnobip** [comment]
Actually, we probably don't want it to run at all outside of tests, even when running in node, so maybe we should add an if that checks some env var to see if we're in test, like `NODE_ENV == "TEST"`, what do you think?

**Comment by wokalski** [comment]
Great idea @tsnobip. The only problem will be fighting the imports, we're gonna need some stubs.

**Comment by tsnobip** [comment]
What's the issue with imports?

**Comment by wokalski** [comment]
```
@inline_test
Zora.test...
```

Will compile to

```
import { test } from "zora"

if (node_env == "test") {
  test(...
}
```

Importing zora might cause side effects which will throw or have different undesired side effects in the browser.
